--DROP TABLES
DROP TABLE BOOT CASCADE CONSTRAINTS;
DROP TABLE MEER CASCADE CONSTRAINTS;
DROP TABLE GEBRUIKER CASCADE CONSTRAINTS;
DROP TABLE ARTIKEL CASCADE CONSTRAINTS;
DROP TABLE HUURCONTRACT CASCADE CONSTRAINTS;
DROP TABLE MEERHUUR CASCADE CONSTRAINTS;
DROP TABLE ARTIKELHUUR CASCADE CONSTRAINTS;
DROP TABLE BOOTHUUR CASCADE CONSTRAINTS;
DROP TABLE MOTORBOOT CASCADE CONSTRAINTS;
DROP TABLE BOOTVERBOD CASCADE CONSTRAINTS;

CREATE TABLE BOOT
(
  BootId NUMBER(10) PRIMARY KEY,
  Naam VARCHAR2(255) UNIQUE,
  Prijs NUMBER(10, 2),
  SoortBoot VARCHAR2(255)
);

CREATE TABLE MEER
(
  MeerId NUMBER(10) PRIMARY KEY,
  Naam VARCHAR2(255) UNIQUE,
  Prijs NUMBER(10, 2)
);

CREATE TABLE GEBRUIKER
(
  GebruikerId NUMBER(10),
  Email VARCHAR2(255) NOT NULL,
  Naam VARCHAR2(64) NOT NULL,
  Wachtwoord VARCHAR2(64)
);

CREATE TABLE HUURCONTRACT
(
  HuurcontractId NUMBER(10) PRIMARY KEY,
  DatumVan DATE,
  DatumTot DATE,
  HuurderId NUMBER(10) NOT NULL
);

CREATE TABLE ARTIKEL 
(
  ArtikelId NUMBER(10) PRIMARY KEY,
  Prijs NUMBER(10, 2),
  Naam VARCHAR2(255)
);

CREATE TABLE ARTIKELHUUR
(
  ArtikelId NUMBER(10),
  HuurcontractId NUMBER(10),
  PRIMARY KEY (ArtikelId, HuurcontractId)
);

CREATE TABLE MOTORBOOT
(
  BootId NUMBER(10) PRIMARY KEY,
  SoortBoot VARCHAR2(255) NOT NULL,
  Tankinhoud NUMBER(10,2)
);

CREATE TABLE MEERHUUR
(
  HuurcontractId NUMBER(10),
  MeerId NUMBER(10),
  PRIMARY KEY (MeerId, HuurcontractId)
);

CREATE TABLE BOOTHUUR
(
  BootId NUMBER(10),
  HuurcontractId NUMBER(10),
  PRIMARY KEY (BootId, HuurcontractId)
);

CREATE TABLE BOOTVERBOD 
(
  BootId NUMBER(10),
  MeerId NUMBER(10),
  PRIMARY KEY (BootId, MeerId)
);

--FOREIGN KEY CONSTRAINTS
ALTER TABLE BOOTHUUR ADD FOREIGN KEY (BootId) REFERENCES BOOT(BootId);
ALTER TABLE BOOTHUUR ADD FOREIGN KEY (HuurcontractId) REFERENCES HUURCONTRACT(HuurcontractId);
ALTER TABLE MEERHUUR ADD FOREIGN KEY (HuurcontractId) REFERENCES HUURCONTRACT(HuurcontractId);
ALTER TABLE MEERHUUR ADD FOREIGN KEY (MeerId) REFERENCES MEER(MeerId);
ALTER TABLE ARTIKELHUUR ADD FOREIGN KEY (ArtikelId) REFERENCES ARTIKEL(ArtikelId);
ALTER TABLE ARTIKELHUUR ADD FOREIGN KEY (HuurcontractId) REFERENCES HUURCONTRACT(HuurcontractId);
ALTER TABLE MOTORBOOT ADD FOREIGN KEY (BootId) REFERENCES BOOT(BootId);
ALTER TABLE BOOTVERBOD ADD FOREIGN KEY (BootId) REFERENCES BOOT(BootId);
ALTER TABLE BOOTVERBOD ADD FOREIGN KEY (MeerId) REFERENCES MEER(MeerId);

--OTHER CONSTRAINTS
ALTER TABLE BOOT ADD CONSTRAINT ck_BOOT_SoortBoot CHECK (
UPPER(SoortBoot) = UPPER('valk') OR 
UPPER(SoortBoot) = UPPER('laser') OR 
UPPER(SoortBoot) = UPPER('kano') OR 
UPPER(SoortBoot) = UPPER('kruiser') OR 
UPPER(SoortBoot) = UPPER('motorboot') OR 
UPPER(SoortBoot) = UPPER('zeilboot'));
ALTER TABLE MOTORBOOT ADD CONSTRAINT ck_MOTORBOOT_SoortBoot CHECK(
UPPER(SoortBoot) = UPPER('motorboot') OR 
UPPER(SoortBoot) = UPPER('kruiser'));
ALTER TABLE HUURCONTRACT ADD CONSTRAINT ck_HUURCONTRACT_datums CHECK(
DatumVan < DatumTot
);

--TRIGGERS AND SEQUENSES
DROP SEQUENCE HuurcontractIncrementSeq;
CREATE SEQUENCE HuurcontractIncrementSeq
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1
 CACHE 20;
/
CREATE OR REPLACE TRIGGER HuurcontractIncrementTrig BEFORE INSERT ON HUURCONTRACT REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE WHEN (new.HuurcontractId IS NULL)
BEGIN
  SELECT HuurcontractIncrementSeq.NEXTVAL INTO :new.HuurcontractId FROM dual;
END;
/

DROP SEQUENCE BootIncrementSeq;
CREATE SEQUENCE BootIncrementSeq
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1
 CACHE 20;
/
CREATE OR REPLACE TRIGGER BootIncrementTrig BEFORE INSERT ON BOOT REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE WHEN (new.BootId IS NULL)
BEGIN
  SELECT BootIncrementSeq.NEXTVAL INTO :new.BootId FROM dual;
END;
/

DROP SEQUENCE MeerIncrementSeq;
CREATE SEQUENCE MeerIncrementSeq
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1
 CACHE 20;
/
CREATE OR REPLACE TRIGGER MeerIncrementTrig BEFORE INSERT ON MEER REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE WHEN (new.MeerId IS NULL)
BEGIN
  SELECT MeerIncrementSeq.NEXTVAL INTO :new.MeerId FROM dual;
END;
/

DROP SEQUENCE ArtikelIncrementSeq;
CREATE SEQUENCE ArtikelIncrementSeq
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1
 CACHE 20;
/
CREATE OR REPLACE TRIGGER ArtikelIncrementTrig BEFORE INSERT ON ARTIKEL REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE WHEN (new.ArtikelId IS NULL)
BEGIN
  SELECT ArtikelIncrementSeq.NEXTVAL INTO :new.ArtikelId FROM dual;
END;
/

DROP SEQUENCE GebruikerIncrementSeq;
CREATE SEQUENCE GebruikerIncrementSeq
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1
 CACHE 20;
/
CREATE OR REPLACE TRIGGER GebruikerIncrementTrig BEFORE INSERT ON GEBRUIKER REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE WHEN (new.GebruikerId IS NULL)
BEGIN
  SELECT GebruikerIncrementSeq.NEXTVAL INTO :new.GebruikerId FROM dual;
END;
/

--Dummy data
INSERT INTO BOOT (Naam, Prijs, SoortBoot) VALUES ('Roeibootje', 10.00, 'kano'); 
INSERT INTO BOOT (Naam, Prijs, SoortBoot) VALUES ('Motorboot 2000', 15.00, 'kruiser');
INSERT INTO MOTORBOOT (BootId, Tankinhoud , SoortBoot) VALUES ('2', 10.00, 'kruiser');

INSERT INTO BOOT (Naam, Prijs, SoortBoot) VALUES ('Zeilbootje Plus', 10.00, 'laser'); 
INSERT INTO BOOT (Naam, Prijs, SoortBoot) VALUES ('Zeilbootje', 10.00, 'valk'); 
INSERT INTO BOOT (Naam, Prijs, SoortBoot) VALUES ('Speedboot', 15.00, 'kruiser');
INSERT INTO MOTORBOOT (BootId, Tankinhoud , SoortBoot) VALUES ('4', 10.00, 'kruiser');

INSERT INTO MEER(Naam, Prijs) VALUES ('Noordzee', 2.00);
INSERT INTO MEER(Naam, Prijs) VALUES ('Ijsselmeer', 2.00);
INSERT INTO MEER(Naam, Prijs) VALUES ('Zuidlaardermeer', 1.00);
INSERT INTO MEER(Naam, Prijs) VALUES ('Veluwemeer', 1.00);
INSERT INTO MEER(Naam, Prijs) VALUES ('Eemmeer', 1.00);
INSERT INTO MEER(Naam, Prijs) VALUES ('Gooimeer', 1.00);

INSERT INTO GEBRUIKER (Email, Naam, Wachtwoord) VALUES ('admin@istrator.nl', 'admin', 'admin');
INSERT INTO GEBRUIKER (Naam, Email) VALUES ('Dummyman', 'dummy@man.nl');

INSERT INTO HUURCONTRACT (DatumVan, DatumTot, HuurderId) VALUES (TO_DATE('01-01-2018', 'DD-MM-YY'), TO_DATE('02-01-2018', 'DD-MM-YY'), 2);

INSERT INTO ARTIKEL (Naam, Prijs) VALUES ('roeispanen', 1.25);
INSERT INTO ARTIKEL (Naam, Prijs) VALUES ('zwemvest', 1.25);

INSERT INTO ARTIKELHUUR (ArtikelId, HuurcontractId) VALUES(1, 1);

INSERT INTO MEERHUUR (MeerId, HuurcontractId) VALUES(1, 1);

INSERT INTO BOOTHUUR (BootId, HuurcontractId) VALUES(1, 1);

INSERT INTO BOOTVERBOD (BootId, MeerId) VALUES ('2', 3);

